"""baseline

Revision ID: a85115d10dba
Revises: 
Create Date: 2026-06-01 02:29:31.166259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a85115d10dba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('oidc_sub', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_oidc_sub'), 'users', ['oidc_sub'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_token_hash'), 'api_tokens', ['token_hash'], unique=True)
    op.create_table('app_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('gdrive_refresh_token', sa.String(), nullable=True),
    sa.Column('gdrive_access_token', sa.String(), nullable=True),
    sa.Column('gdrive_token_expiry', sa.Float(), nullable=True),
    sa.Column('gdrive_sync_folder_id', sa.String(), nullable=True),
    sa.Column('sync_schedule', sa.String(), nullable=False),
    sa.Column('last_sms_modified', sa.String(), nullable=True),
    sa.Column('last_calls_modified', sa.String(), nullable=True),
    sa.Column('last_sync_status', sa.String(), nullable=True),
    sa.Column('last_sync_time', sa.String(), nullable=True),
    sa.Column('last_sync_error', sa.String(), nullable=True),
    sa.Column('last_sync_stats', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_config_user_id'), 'app_config', ['user_id'], unique=False)
    op.create_table('calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('number', sa.Text(), nullable=False),
    sa.Column('normalized_number', sa.Text(), nullable=False),
    sa.Column('contact_name', sa.Text(), nullable=True),
    sa.Column('date_ms', sa.BigInteger(), nullable=False),
    sa.Column('readable_date', sa.String(length=64), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('presentation', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_hash'), 'calls', ['hash'], unique=True)
    op.create_index(op.f('ix_calls_normalized_number'), 'calls', ['normalized_number'], unique=False)
    op.create_index(op.f('ix_calls_number'), 'calls', ['number'], unique=False)
    op.create_index(op.f('ix_calls_user_id'), 'calls', ['user_id'], unique=False)
    op.create_table('mms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('normalized_address', sa.Text(), nullable=False),
    sa.Column('contact_name', sa.Text(), nullable=True),
    sa.Column('date_ms', sa.BigInteger(), nullable=False),
    sa.Column('readable_date', sa.String(length=64), nullable=True),
    sa.Column('msg_box', sa.SmallInteger(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('ct_t', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mms_address'), 'mms', ['address'], unique=False)
    op.create_index(op.f('ix_mms_hash'), 'mms', ['hash'], unique=True)
    op.create_index(op.f('ix_mms_normalized_address'), 'mms', ['normalized_address'], unique=False)
    op.create_index(op.f('ix_mms_user_id'), 'mms', ['user_id'], unique=False)
    op.create_table('sms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('normalized_address', sa.Text(), nullable=False),
    sa.Column('contact_name', sa.Text(), nullable=True),
    sa.Column('date_ms', sa.BigInteger(), nullable=False),
    sa.Column('readable_date', sa.String(length=64), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('read', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('service_center', sa.Text(), nullable=True),
    sa.Column('sub_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_address'), 'sms', ['address'], unique=False)
    op.create_index(op.f('ix_sms_hash'), 'sms', ['hash'], unique=True)
    op.create_index(op.f('ix_sms_normalized_address'), 'sms', ['normalized_address'], unique=False)
    op.create_index(op.f('ix_sms_user_id'), 'sms', ['user_id'], unique=False)
    op.create_table('mms_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mms_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.SmallInteger(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['mms_id'], ['mms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mms_parts')
    op.drop_index(op.f('ix_sms_user_id'), table_name='sms')
    op.drop_index(op.f('ix_sms_normalized_address'), table_name='sms')
    op.drop_index(op.f('ix_sms_hash'), table_name='sms')
    op.drop_index(op.f('ix_sms_address'), table_name='sms')
    op.drop_table('sms')
    op.drop_index(op.f('ix_mms_user_id'), table_name='mms')
    op.drop_index(op.f('ix_mms_normalized_address'), table_name='mms')
    op.drop_index(op.f('ix_mms_hash'), table_name='mms')
    op.drop_index(op.f('ix_mms_address'), table_name='mms')
    op.drop_table('mms')
    op.drop_index(op.f('ix_calls_user_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_number'), table_name='calls')
    op.drop_index(op.f('ix_calls_normalized_number'), table_name='calls')
    op.drop_index(op.f('ix_calls_hash'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_app_config_user_id'), table_name='app_config')
    op.drop_table('app_config')
    op.drop_index(op.f('ix_api_tokens_token_hash'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_oidc_sub'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
